In [40]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings

warnings.filterwarnings('ignore')

In [41]:
df=pd.read_csv('heart.csv')

In [42]:
df.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0

In [43]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score,f1_score,classification_report

In [44]:
df.columns

Index(['Age', 'Sex', 'ChestPainType', 'RestingBP', 'Cholesterol', 'FastingBS',
       'RestingECG', 'MaxHR', 'ExerciseAngina', 'Oldpeak', 'ST_Slope',
       'HeartDisease'],
      dtype='object')

In [45]:
df_encoded = pd.get_dummies(
    df,
    columns=['Sex','ChestPainType','RestingECG','ExerciseAngina','ST_Slope'],
    drop_first=True
)

In [46]:
X=df_encoded.drop('HeartDisease',axis=1)
y=df_encoded['HeartDisease']

In [47]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [48]:
X_train=X_train.astype(int)
X_test=X_test.astype(int)

In [49]:
X_train

,Age,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,Sex_M,ChestPainType_ATA,ChestPainType_NAP,RestingECG_Normal,RestingECG_ST,ExerciseAngina_Y,ST_Slope_Flat,ST_Slope_Up
8,61,145,260,1,115,2,1,0,0,0,0,1,0,0
5,45,128,205,0,170,0,1,1,0,1,0,0,0,1
11,47,142,250,1,130,1,1,0,0,1,0,1,1,0
3,48,138,214,0,108,1,0,0,0,1,0,1,1,0
18,57,136,220,0,142,0,1,0,1,1,0,0,0,1
16,60,148,255,1,118,2,0,0,0,0,0,1,1,0
13,63,150,270,1,110,3,1,0,0,0,0,1,0,0
2,37,130,283,0,98,0,1,1,0,0,1,0,0,1
9,39,120,190,0,165,0,0,1,0,1,0,0,0,1
19,65,155,280,1,105,3,0,0,0,0,0,1,0,0
4,54,150,195,0,122,0,1,0,1,1,0,0,0,1
12,50,135,225,0,155,0,0,0,1,1,0,0,0,1
7,52,134,210,0,150,0,1,0,1,1,0,0,0,1
10,58,138,230,0,140,1,1,0,1,0,1,0,1,0
14,44,118,185,0,175,0,0,1,0,1,0,0,0,1
6,56,140,240,1,120,2,0,0,0,0,0,1,1,0

In [50]:
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [51]:
X_train

array([[ 1.07148436,  0.69275631,  0.9106594 ,  1.29099445, -0.74291011,
         0.97662448,  0.8819171 , -0.57735027, -0.67419986, -1.13389342,
        -0.37796447,  1.13389342, -0.67419986, -1.        ],
       [-0.88780132, -0.9747633 , -0.87813585, -0.77459667,  1.56719906,
        -0.86172748,  0.8819171 ,  1.73205081, -0.67419986,  0.8819171 ,
        -0.37796447, -0.8819171 , -0.67419986,  1.        ],
       [-0.64289061,  0.39848814,  0.5854239 ,  1.29099445, -0.11288033,
         0.0574485 ,  0.8819171 , -0.57735027, -0.67419986,  0.8819171 ,
        -0.37796447,  1.13389342,  1.4832397 , -1.        ],
       [-0.52043526,  0.00613059, -0.5854239 , -0.77459667, -1.036924  ,
         0.0574485 , -1.13389342, -0.57735027, -0.67419986,  0.8819171 ,
        -0.37796447,  1.13389342,  1.4832397 , -1.        ],
       [ 0.58166294, -0.19004819, -0.3902826 , -0.77459667,  0.39114349,
        -0.86172748,  0.8819171 , -0.57735027,  1.4832397 ,  0.8819171 ,
        -0.37796447, -0.8819171 , -0.67419986,  1.        ],
       [ 0.949029  ,  0.98702447,  0.74804165,  1.29099445, -0.61690415,
         0.97662448, -1.13389342, -0.57735027, -0.67419986, -1.13389342,
        -0.37796447,  1.13389342,  1.4832397 , -1.        ],
       [ 1.31639507,  1.18320325,  1.2358949 ,  1.29099445, -0.95292003,
         1.89580047,  0.8819171 , -0.57735027, -0.67419986, -1.13389342,
        -0.37796447,  1.13389342, -0.67419986, -1.        ],
       [-1.86744416, -0.77858452,  1.65870105, -0.77459667, -1.45694385,
        -0.86172748,  0.8819171 ,  1.73205081, -0.67419986, -1.13389342,
         2.64575131, -0.8819171 , -0.67419986,  1.        ],
       [-1.62253345, -1.75947841, -1.3659891 , -0.77459667,  1.35718914,
        -0.86172748, -1.13389342,  1.73205081, -0.67419986,  0.8819171 ,
        -0.37796447, -0.8819171 , -0.67419986,  1.        ],
       [ 1.56130578,  1.67365019,  1.5611304 ,  1.29099445, -1.16292996,
         1.89580047, -1.13389342, -0.57735027, -0.67419986, -1.13389342,
        -0.37796447,  1.13389342, -0.67419986, -1.        ],
       [ 0.21429687,  1.18320325, -1.20337135, -0.77459667, -0.44889621,
        -0.86172748,  0.8819171 , -0.57735027,  1.4832397 ,  0.8819171 ,
        -0.37796447, -0.8819171 , -0.67419986,  1.        ],
       [-0.27552455, -0.28813758, -0.22766485, -0.77459667,  0.93716929,
        -0.86172748, -1.13389342, -0.57735027,  1.4832397 ,  0.8819171 ,
        -0.37796447, -0.8819171 , -0.67419986,  1.        ],
       [-0.03061384, -0.38622697, -0.7155181 , -0.77459667,  0.72715936,
        -0.86172748,  0.8819171 , -0.57735027,  1.4832397 ,  0.8819171 ,
        -0.37796447, -0.8819171 , -0.67419986,  1.        ],
       [ 0.70411829,  0.00613059, -0.0650471 , -0.77459667,  0.30713952,
         0.0574485 ,  0.8819171 , -0.57735027,  1.4832397 , -1.13389342,
         2.64575131, -0.8819171 ,  1.4832397 , -1.        ],
       [-1.01025668, -1.95565719, -1.52860685, -0.77459667,  1.77720899,
        -0.86172748, -1.13389342,  1.73205081, -0.67419986,  0.8819171 ,
        -0.37796447, -0.8819171 , -0.67419986,  1.        ],
       [ 0.45920758,  0.20230936,  0.2601884 ,  1.29099445, -0.53290018,
         0.97662448, -1.13389342, -0.57735027, -0.67419986, -1.13389342,
        -0.37796447,  1.13389342,  1.4832397 , -1.        ]])

In [52]:
models={
    "Logisctic":LogisticRegression(),
    "KNN":KNeighborsClassifier(),
    "Naive_bayes":GaussianNB(),
    "SVM":SVC(),
    "Tree":DecisionTreeClassifier()
}

In [53]:
result=[]

In [54]:
for name,model in models.items():
    model.fit(X_train,y_train)
    y_pred=model.predict(X_test)
    acc=accuracy_score(y_pred,y_test)
    f1=f1_score(y_pred,y_test)
    result.append({
        "name":name,
        "accuracy_score":round(acc,4),
        "f1_score":f1
    })

In [55]:
result

[{'name': 'Logisctic', 'accuracy_score': 1.0, 'f1_score': 1.0},
 {'name': 'KNN', 'accuracy_score': 0.5, 'f1_score': 0.0},
 {'name': 'Naive_bayes', 'accuracy_score': 1.0, 'f1_score': 1.0},
 {'name': 'SVM', 'accuracy_score': 1.0, 'f1_score': 1.0},
 {'name': 'Tree', 'accuracy_score': 1.0, 'f1_score': 1.0}]

In [56]:
import joblib

In [59]:
joblib.dump(models['Logisctic'],"Logistic_heart.pkl")
joblib.dump(scaler,"scaler.pkl")
joblib.dump(X.columns.tolist(),"columns.pkl")

['columns.pkl']